SELECT i.FLAVOR
FROM icecream_info i
JOIN first_half f ON i.FLAVOR = f.FLAVOR
WHERE i.INGREDIENT_TYPE = 'fruit_based'
GROUP BY i.FLAVOR
HAVING SUM(f.TOTAL_ORDER) >= 3000
ORDER BY SUM(f.TOTAL_ORDER) DESC;